/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary */

#ifndef _Included_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
#define _Included_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
 * Method:    socket
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary_socket
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
 * Method:    bind
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary_bind
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
 * Method:    listen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary_listen
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
 * Method:    accept
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary_accept
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
 * Method:    connect
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary_connect
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
 * Method:    read
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary_read
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
 * Method:    write
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary_write
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary
 * Method:    shutdown
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibrary_shutdown
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
