/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider */

#ifndef _Included_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
#define _Included_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    socket
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_socket
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    bind
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_bind
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    listen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_listen
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    accept
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_accept
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    connect
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_connect
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_read
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_write
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider
 * Method:    shutdown
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider_shutdown
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
